### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by WonkySpecs** [WonkySpecs/go-game#1]
With all of these done, I'll call the project finished:
- [x] Check for ko
- [ ] CLI, as alternative to interactive mode
- [ ] Choosable board size
- [ ] Stone textures (with random rotations)
- [x] Ghost stone on hover
- [x] Pass button + game end
- [ ] Build executable
- [ ] Basic doc
- [x] Error messages for invalid moves

Optional extras:
- [ ] Scoring
- [ ] GUI interface for hosting/joining
- [ ] Less simplistic background
- [ ] Timer
- [ ] Resizable screen
- [ ] Better (network) error handling

Highly unlikely in the forseeable future:
- [ ] Tests
- [ ] Messaging
- [ ] Game logs
- [ ] Non networked play (AI?)
